baseURL = "zialdiansyah.github.io"
languageCode = "en-us"
title = "Zia Ulhafizd Aldiansyah"
theme = "hello-friend-ng"
enableSharingButtons = true
disableRSS  = true

[[menu.main]]
  identifier = "posts"
  name       = "Blog"
  url        = "posts/"

[params]
  homeSubtitle = "Currently working as Frontend developer at <a href=\"https://vutura.io\">vutura.io</a>"
  footerLeft = "Powered by <a href=\"http://gohugo.io\">Hugo</a> using <a href=\"https://themes.gohugo.io/hugo-theme-hello-friend-ng/\">hello-friend-ng</a> theme"
  footerRight = "Made with &#10084; at Bandung"

  [params.logo]
    logoText = "zialdiansyah"

[[params.social]]
    name = "email"
    url  = "mailto:ziaulhafizda@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/zialdiansyah"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/zia-aldiansyah/"